apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "alerta.fullname" . }}
  labels:
    app: {{ template "alerta.name" . }}
    chart: {{ template "alerta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "alerta.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "alerta.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_URI
              value: mongodb://{{ template "alerta.fullname" . }}-mongodb:27017/monitoring
            - name: CORS_ORIGINS
              value: {{ range $index, $element := .Values.ingress.hosts }}{{- if $index}},{{- end }}{{ $element }}{{- end }}
              {{- if .Values.alertaAdminUsers }}
            - name: ADMIN_USERS
              value: {{ range $index, $element := .Values.alertaAdminUsers }}{{- if $index}},{{- end }}{{ $element }}{{- end }}
              {{- end }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "alerta.fullname" . }}
                  key: alerta-admin-password
            - name: PLUGINS
              value: {{ range $index, $element := .Values.alertaPlugins }}{{- if $index}},{{- end }}{{ $element }}{{- end }}
            - name: INSTALL_PLUGINS
              value: {{ range $index, $element := .Values.alertaInstallPlugins }}{{- if $index}},{{- end }}{{ $element }}{{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
