apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # the serviceAccountName is used only in rbac clusters
      serviceAccountName: bigip-ctlr-serviceaccount
      containers:
        - name: k8s-bigip-ctlr
          # replace the version as needed
          image: '{{.Values.image.repository}}:{{.Values.image.version}}'
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          command: ["/app/bin/k8s-bigip-ctlr"]
          env:
            # Get sensitive values from the bigip-credentials secret
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-credentials
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-credentials
                  key: password
            - name: BIGIP_URL
              valueFrom:
                secretKeyRef:
                  name: bigip-credentials
                  key: url
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=$(BIGIP_URL)",
            "--bigip-partition={{required 'You must specify a bigip-partition to control' .Values.bigip.partition}}",
            "--log-level={{.Values.bigip.loglevel}}",
            {{- if Values.bigip.defaultip }}
            "--default-ingress-ip={{.Values.bigip.defaultip}}",
            {{- end }}
            {{- if .Values.bigip.dnsserver }}
            "--resolve-ingress-names={{.Values.bigip.dnsserver}}"
            {{- end }}
            ]
