apiVersion: v1
kind: Secret
metadata:
  name: bigip-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ required "You must specify a bigip URL" .Values.bigip.url | b64enc | quote }}
  username: {{ required "You must specify a bigip username" .Values.bigip.username | b64enc | quote }}
  password: {{ required "You must specify a bigip password" .Values.bigip.password | b64enc | quote }}
