apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cachet.fullname" . }}
  labels:
    app: {{ template "cachet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  cachet-key:  {{ required "Please specify a cachet key - generate it using `php artisan key:generate`" .Values.cachetKey | b64enc | quote }}
